GET http://localhost:3100/dogs

###

GET http://localhost:3100/dogs/id

###
POST http://localhost:3100/add

###
PUT http://localhost:3100/dogs/id

###
PUT http://localhost:3100/add
Content-Type: application/json

      
          {
            "dogName": "Tomten",
            "breed": "Golden Reitriver",
            "owner": "Potta",
            "email": "pottan@gmail.com",
            "id": "uuid"
          };

###
DELETE http://localhost:3100/dogs/574007c8-d5c9-4625-b321-0e1ea217c939



