GET http://localhost:3100/dogs
###


GET http://localhost:3100/dogs/8
###

POST http://localhost:3100/dogs/dogName
Content-Type: application/json

{
    "dogName": "NY DOfG",
    "breed": "ddd",
    "owner": "ddd",
    "email": "ddd",
    "id": "38669"
}

###
PUT http://localhost:3100/dogs/id
Content-Type: application/json

{
    "dogName": "Kalle",
    "breed": "Golden",
    "owner": "Melwin",
    "email": "melwin@gmail.com",
    "id": "123"
}
###

DELETE http://localhost:3100/dogs/id
Content-Type: application/json

{
    "id": "38669"
}
###