GET http://localhost:3100/
###

GET http://localhost:3100/dogs
###

GET http://localhost:3100/dogs/id

###
POST http://localhost:3100/add

###

DELETE http://localhost:3100/dogs/9

###
###
PUT http://localhost:3100/dogs
Content-Type: application/json

      
{
    "dogName": "Tomten",
    "breed": "Golden Reitriver",
    "owner": "Potta",
    "email": "pottan@gmail.com",
    "id": "uuid"    
}
###
GET http://localhost:3100/dogs/9
###

POST http://localhost:3100/add

###

